name: Pull Request Check
on:
  pull_request:
    branches: [master, develop]

jobs:
  check-pr:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run Prettier check
        run: npm run prettier
      - name: Run ESlint check
        run: npm run lint
